### ISSUE TITLE
Batterylog doesn't work on Jolla C phone

### ISSUE THREAD

**Issue by wdobbe** [zeburon/sailfish-batterylog#3]
Yesterday I received my Jolla C and installed Sailfish-batterylog.

Even though it is running for several hours, the GUI still says:

> ?
> calculating...
> ?
> when fully charged

I will try to debug this weekend or next week if I have time.

**Comment by zeburon** [comment]
Unfortunately I do not have access to a Jolla C :(
Is any other information displayed, like for instance current, voltage or status?

On a Jolla 1 the information is extracted from the following files:

## battery

**directory:** /sys/class/power_supply/battery/
**files:** capacity, current_now, voltage_now, energy_now, energy_full, energy_full_design, status, health

## display

**directory:** /sys/class/leds/lcd-backlight/
**file:** brightness

Are these files present on a Jolla C?

**Comment by wdobbe** [comment]
No, enerygy_xxx sysfs files are not present:

```
[nemo@Sailfish battery]$ pwd
/sys/class/power_supply/battery
[nemo@Sailfish battery]$ ls -l
total 0
-rw-r--r-- 1 root root 4096 Jul 19 09:53 capacity
-r--r--r-- 1 root root 4096 Jul 19 22:41 charge_type
-rw-r--r-- 1 root root 4096 Jul 19 22:41 charging_enabled
-r--r--r-- 1 root root 4096 Jul 19 09:53 current_now
lrwxrwxrwx 1 root root    0 Jul 19 22:47 device -> ../../../qpnp-linear-charger-f4bca200
-r--r--r-- 1 root root 4096 Jul 19 09:53 health
drwxr-xr-x 2 root root    0 Jul 19 22:41 power
-r--r--r-- 1 root root 4096 Jul 19 09:53 present
-rw-r--r-- 1 root root 4096 Jul 19 09:53 status
lrwxrwxrwx 1 root root    0 Jul 19 22:47 subsystem -> ../../../../../class/power_supply
-rw-r--r-- 1 root root 4096 Jul 19 22:41 system_temp_level
-r--r--r-- 1 root root 4096 Jul 19 09:53 temp
-rw-r--r-- 1 root root 4096 Jul 19 22:41 temp_cool
-rw-r--r-- 1 root root 4096 Jul 19 22:41 temp_warm
-r--r--r-- 1 root root 4096 Jul 19 09:53 type
-rw-r--r-- 1 root root 4096 Jan  1  1970 uevent
-r--r--r-- 1 root root 4096 Jul 19 22:41 voltage_max_design
-r--r--r-- 1 root root 4096 Jul 19 22:41 voltage_min_design
-r--r--r-- 1 root root 4096 Jul 19 09:53 voltage_now
```

**Comment by zeburon** [comment]
Well, that explains the issue :)

Does any other directory contain energy_xxx files?

**Comment by wdobbe** [comment]
Unfortunately not, as far as I can tell ...
Well, the Jolla C costed only 160 euro, so I guess they had to save money somewhere...

```
[nemo@Sailfish sys]$ pwd
/sys
[nemo@Sailfish sys]$ find . -name energy_*
find: ./fs/fuse/connections/28: Permission denied
[nemo@Sailfish sys]$ find . -name voltage_*
find: ./fs/fuse/connections/28: Permission denied
./devices/soc.0/qpnp-linear-charger-f4bca200/power_supply/battery/voltage_max_design
./devices/soc.0/qpnp-linear-charger-f4bca200/power_supply/battery/voltage_now
./devices/soc.0/qpnp-linear-charger-f4bca200/power_supply/battery/voltage_min_design
./devices/soc.0/qpnp-vm-bms-f4bca600/power_supply/bms/voltage_ocv
./devices/soc.0/78d9000.usb/power_supply/usb/voltage_max
./devices/soc.0/78d9000.usb/power_supply/usb/voltage_now
```

**Comment by zeburon** [comment]
Does Battery Log display the capacity (in percent), current, voltage, status (charging / discharging) and health? Provided the available files are valid , I can implement a workaround for the Jolla C:

energy_full_design = 9500mWh
energy_now = capacity \* energy_full_design

_energy_full instead of energy_full_design would be more accurate (degraded energy_full_design value - the energy level the battery is actually able to reach)_

Not as accurate as on a Jolla 1, but it's a guesstimate anyway :)

**Comment by wdobbe** [comment]
Yes, all of those measurements are valid. See attached screenshots.

Thanks in advance for patching !
![battery_log_on_jolla_c](https://cloud.githubusercontent.com/assets/19475596/17040713/b505346a-4fa1-11e6-9d28-d3c510bb1634.jpg)
![battery_log_on_jolla_c_2](https://cloud.githubusercontent.com/assets/19475596/17040810/2e41334c-4fa2-11e6-9df5-bb4e2df088df.jpg)

**Comment by zeburon** [comment]
Could you please do me a favor and list the files present in **/run/state/namespaces/Battery/**
I am particularly interested in the contents of
- Energy
- EnergyFull
- ChargePercent

... if they exist :)

**Comment by wdobbe** [comment]
Sure, the files exist and seem to have a valid contents:

```
[nemo@Sailfish Battery]$ pwd
/run/state/namespaces/Battery
[nemo@Sailfish Battery]$ ls -l
total 0
lrwxrwxrwx 1 root privileged 37 Jul 25 12:12 Capacity -> ../../providers/udev/Battery/Capacity
lrwxrwxrwx 1 root privileged 45 Jul 25 12:12 ChargePercentage -> ../../providers/udev/Battery/ChargePercentage
lrwxrwxrwx 1 root privileged 40 Jul 25 12:12 ChargerType -> ../../providers/udev/Battery/ChargerType
lrwxrwxrwx 1 root privileged 42 Jul 25 12:12 ChargingState -> ../../providers/udev/Battery/ChargingState
lrwxrwxrwx 1 root privileged 36 Jul 25 12:12 Current -> ../../providers/udev/Battery/Current
lrwxrwxrwx 1 root privileged 35 Jul 25 12:12 Energy -> ../../providers/udev/Battery/Energy
lrwxrwxrwx 1 root privileged 39 Jul 25 12:12 EnergyFull -> ../../providers/udev/Battery/EnergyFull
lrwxrwxrwx 1 root privileged 39 Jul 25 12:12 IsCharging -> ../../providers/udev/Battery/IsCharging
lrwxrwxrwx 1 root privileged 34 Jul 25 12:12 Level -> ../../providers/udev/Battery/Level
lrwxrwxrwx 1 root privileged 39 Jul 25 12:12 LowBattery -> ../../providers/udev/Battery/LowBattery
lrwxrwxrwx 1 root privileged 38 Jul 25 12:12 OnBattery -> ../../providers/udev/Battery/OnBattery
lrwxrwxrwx 1 root privileged 34 Jul 25 12:12 Power -> ../../providers/udev/Battery/Power
lrwxrwxrwx 1 root privileged 34 Jul 25 12:12 State -> ../../providers/udev/Battery/State
lrwxrwxrwx 1 root privileged 40 Jul 25 12:12 Temperature -> ../../providers/udev/Battery/Temperature
lrwxrwxrwx 1 root privileged 42 Jul 25 12:12 TimeUntilFull -> ../../providers/udev/Battery/TimeUntilFull
lrwxrwxrwx 1 root privileged 41 Jul 25 12:12 TimeUntilLow -> ../../providers/udev/Battery/TimeUntilLow
lrwxrwxrwx 1 root privileged 36 Jul 25 12:12 Voltage -> ../../providers/udev/Battery/Voltage
[nemo@Sailfish Battery]$ cat Energy
1086800[nemo@Sailfish Battery]$ cat EnergyFull
8360000[nemo@Sailfish Battery]$ cat ChargePercentage
13[nemo@Sailfish Battery]$
```

**Comment by zeburon** [comment]
Thank you very much!

"Energy" on my Jolla 1 contains a strange value. Guess I will have to mix sysfs & statefs and perform some sanity checks.

**Comment by zeburon** [comment]
Could you please try out version [1.3.1](https://github.com/zeburon/sailfish-batterylog/releases/tag/v1.3.1)?
I have attached a zip file which contains the rpm package (not allowed to attach rpm files...)
If it works I can publish it on Jolla Harbour

**Comment by blabber** [comment]
Hi. I tried version 1.3.1 on my Jolla C and it looks exactly like the screenshots in https://github.com/zeburon/sailfish-batterylog/issues/3#issuecomment-234402160

mWh is 0 and all percentages in the protocol view are 0%, no graph is plotted.

**Comment by blabber** [comment]
Read some of your code to check what might be wrong and found following: `/run/state/namespaces/Battery/energy_now` and `/run/state/namespaces/Battery/energy_full` do not exist.

With regard to https://github.com/zeburon/sailfish-batterylog/issues/3#issuecomment-235062767 it seems like you intended to use `/run/state/namespaces/Battery/Energy` and `/run/state/namespaces/Battery/EnergyFull` (which are existent).

**Comment by zeburon** [comment]
You are absolutely right - nice copy&paste error. Thank you for noticing the bug :)

I have created a new release [1.3.2](https://github.com/zeburon/sailfish-batterylog/releases/tag/v1.3.2)

**Comment by blabber** [comment]
Looks much better. I will test a little more and report back this evening.

![screenshot_20160815_001](https://cloud.githubusercontent.com/assets/1199257/17660947/614631aa-62dc-11e6-8b0b-8ccbf4c48c75.png)

**Comment by blabber** [comment]
Works as expected for me. :+1: 

Thanks for supporting Jolla C/Aqua Fish and thanks for the app, it's a must have!

**Comment by zeburon** [comment]
Great! If you do not encounter any new bugs in the next couple of days I will upload this release to Jolla Harbour.

**Comment by blabber** [comment]
Still no problems. I would say: Ship it! :+1:

**Comment by zeburon** [comment]
Excellent! 1.3.2 has just been submitted to Jolla Harbour.

Thank you very much for your help!
